web_ui/ruby/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/general_statistics', to: 'general_statistics#index'
  get    '/daily_statistics',   to: 'daily_statistics#index'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'

  namespace :api do
    get    '/general_statistics', to: 'general_statistics#index'
    get    '/daily_statistics',   to: 'daily_statistics#index'

    resources :keyword, only: [:show, :destroy, :update, :index]
    resources :site, only: [:show, :destroy, :update, :index, :create]

    resources :person, only: [:show, :destroy, :update, :index, :create] do
      resources :keyword, only: [:create]
    end

  end

end

web_ui/ruby/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Разработано компанией <a href="https://github.com/Creative-and-quality">Creative-and-quality</a>
  </small>
</footer>

web_ui/ruby/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Rating-Service-Production", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Помощь", '#' %></li>
        <li><%= link_to "К статистике", general_statistics_path %></li>
        <% if logged_in? %>
            <li>
              <%= link_to "Выход", logout_url, method: "delete" %>
            </li>
        <% else %>
            <li><%= link_to "Войти", login_url %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

web_ui/ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RspWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </div>


</body>
</html>