web_ui/ruby/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/general_statistics', to: 'general_statistics#index'
  get    '/daily_statistics',   to: 'daily_statistics#index'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'

  namespace :api do
    get    '/general_statistics', to: 'general_statistics#index'
    get    '/daily_statistics',   to: 'daily_statistics#index'

    resources :keyword, only: [:show, :destroy, :update, :index]
    resources :site, only: [:show, :destroy, :update, :index, :create]

    resources :person, only: [:show, :destroy, :update, :index, :create] do
      resources :keyword, only: [:create]
    end

  end

end

web_ui/ruby/app/views/shared/_count_page_table.html.erb
<% if @last_person %>


<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Дата</th><th>Кол-во новых страниц <%= print_date_range(@date_range) %></th>
    </tr>
  </thead>
  <tbody>
    <% count_page_on_date_and_site(@last_person, @last_site, @date_range).each_pair do |date, count| %>
    <tr>
      <td><%= date %></td><td><%= count %></td>
    </tr>

    <%end%>

  </tbody>
</table>

<% end %>

web_ui/ruby/app/views/shared/_error_message.html.erb
<% if @error_message[:error] %>
<div class="alert alert-danger">
  <ul>
    <% @error_message[:error].each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

web_ui/ruby/app/views/shared/_google_charts.html.erb
<script src="https://www.google.com/jsapi"></script>

web_ui/ruby/app/views/shared/_left_menu.html.erb
<div class="col-md-2 sidebar main_menu">
  <ul class="nav nav-sidebar">
    <li class= <%= 'active' if @BUTTEN_ACTIVE == 'G'%> >
      <%= link_to "Общая статистика", general_statistics_path %>
        <span class="sr-only">(current)</span>
      </a>
    </li>
    <li class= <%= 'active' if @BUTTEN_ACTIVE == 'D' %> >
      <%= link_to "Ежедневная статистика", daily_statistics_path %>
        <span class="sr-only">(current)</span>
      </a>
    </li>
  </ul>
</div>

web_ui/ruby/app/views/shared/_persons_table.html.erb
<% if @last_site %>


<table class="table table-bordered table-hover table-striped" id="persons_rank">
  <thead>
    <tr>
      <th>Имя персоны</th><th>Кол-во упоменаний на сайте</th>
    </tr>
  </thead>
  <tbody>
    <% persons_table(@persons, @last_site.id).each_pair do |name, rank| %>
    <tr>
      <td name="person"><%= name %></td><td name="rank"><%= rank %></td>
    </tr>

    <%end%>

  </tbody>
</table>

<% end %>